#配置启动端口
server:
  port: 8080
  servlet:
    context-path: /member

#数据源配置
spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 1000

  #设置热部署
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false #页面不加载缓存，修改即时生效

#自定义数据源
custom:
  datasource:
    names: dss1,dss2
    dss1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/slave1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
    dss2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/slave2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root

#日志配置
logging:
  level:
    com.lz: debug
    org.springfromework: debug
  #file: app.log

#资源认证配置
security:
  oauth2:
    client:
      client-id: MemberSystem
      client-secret: 123456
      access-token-uri: http://127.0.0.1:8089/oauth/token
      user-authorization-uri: http://127.0.0.1:8089/oauth/authorize
    resource:
      user-info-uri: http://127.0.0.1:8089/user/me